### ISSUE TITLE
xml.etree.ElementTree.ParseError: mismatched tag: line 33, column 2

### ISSUE THREAD

**Issue by jsebt** [JakeLunn/one-pace-plex-assistant#12]
![image](https://github.com/JakeLunn/one-pace-plex-assistant/assets/26907216/de740b1c-35b4-437e-bab5-fca4b2624093)

setup-media worked, but setup-plex throws the above error.

(and yes I know I uploaded a screenshot with my token, I rotated it out already.)<
let me know if you need more info.

**Comment by JakeLunn** [comment]
Thank you for reporting this, will take a look at this today.

**Comment by sameetandpotatoes** [comment]
I'm having the same issue btw, it seems to be happening on initializing PlexServer.
```
plex = PlexServer(args.plex_host, args.plex_token)
```

I wonder if using an older (or maybe newer?) version of the library helps?

**Comment by HeavenlyDemon100** [comment]
Happens to me as well. Any updates on this?

Edit: I've found a very simple fix. Just remove the /web from the plex host url. Worked like a charm

![image](https://github.com/JakeLunn/one-pace-plex-assistant/assets/107574383/d304257f-fd26-4f2a-9cf0-d70c18ddeb60)

**Comment by JakeLunn** [comment]
I looked into this and tried to recreate it locally but wasn't able to recreate. It looks like it might be due to the URL being incorrect, as pointed out by @HeavenlyDemon100 . If anyone else runs into the issue and is unable to resolve it by double checking their server's host URL - please reply here and let me know.

One thing I recommend doing is visiting your host URL in the browser and verify the server loads, there are no redirects to other locations, and all necessary ports are also unblocked on the target machine.
